server:
  port: 24130

issue:
  service:
    url: http://localhost:24110

spring:
  cassandra:
    port: 9042
    keyspace-name: issue_keyspace
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
    contact-points: localhost:9042
    url: jdbc:cassandra://localhost:9042/issue_keyspace?localdatacenter=datacenter1
    username: cassandra
    password: cassandra
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "by.symonik.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



#    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
#  datasource:
#    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
#    name: cassandra_datasource

#  CREATE TABLE tbl_comment (country text, id bigint, issue_id bigint, content text, PRIMARY KEY ((country), id, issue_id ));